### ISSUE TITLE
disclosure_dataframe Usage example gives "UnboundLocalError"

### ISSUE THREAD

**Issue by luceydav** [calcbench/python_api_client#13]
Hi, 
This is the example straight from the documentation and same result when I tried the "disclosure_nlp.ipynb" notebook:

```
import calcbench as cb
data = cb.disclosure_dataframe(
company_identifiers=["msft", "goog"],
all_history=True,  
disclosure_names=["ManagementsDiscussionAndAnalysis", "RiskFactors"])  
UnboundLocalError: local variable 'quarter' referenced before assignment
```

**Comment by andrewkittredge** [comment]
you need to specify a period_type.  I fixed the example and added a check to the code.

data = calcbench.disclosure_dataframe(company_identifiers=["msft", "goog"],
                                    all_history=True,
                                    disclosure_names=["ManagementsDiscussionAndAnalysis", "RiskFactors"],
                                    period_type="annual")
